name: TestWorkflow
# workflow_dispatch only for main branch
on:
    workflow_dispatch
    # schedule:
        # - cron: "5 * * * *"
    # pull_request:
        # types:
            # - opened
        # branches:
            # - main
            # - !'develop'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            # - name: print
            - name: Setup Java JDK
              uses: actions/setup-java@v5.2.0
              with:
                  java-version: "17"
                  distribution: "microsoft"
              # run: echo "Welcome to Github Actions!! - Manuall trigger added"

    test:
        runs-on: ubuntu-latest

        steps:
            - name: Display
              run: echo "My manual testing workflow updated ${{ github }}"
